# Generated by Django 3.2.8 on 2021-11-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20211101_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='full_name',
            field=models.CharField(default='', max_length=30, verbose_name='full_name'),
        ),
    ]
