# Generated by Django 3.2.8 on 2021-11-11 18:21

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=users.models.get_default_profile_image, upload_to=users.models.get_profile_image_file_path),
        ),
    ]
