# Generated by Django 3.2.8 on 2021-10-31 07:47

import account.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name=account.models.Account),
        ),
    ]
